spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/security_jwt
    username:
      root
    password:
    driver:
      class:
        com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    databese: mysql
    database-plataform: org.hibernate.dialect.MySQL8InnoDBDialect